"Name: ÎâÉñÒ½ ID: 389 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_Ò©µêÀÏ°å¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: B¾c ®Èu l·o nh©n ID: 715 Script: \script\event\springfestival08\allbrother\beidoulaoren.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: TiÕp §Çu C«ng Thµnh ChiÕn ID: 950 Script: \script\missions\sevencity\dialog_npc.lua DropFile:  Life: 100 NguHanh: 4 Kind: 3"
"Name: NhiÕp Thİ TrÇn ID: 769 Script: \script\task\tollgate\killer\nieshichen.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: Ç®×¯ÀÏ°å ID: 391 Script: \script\Î÷±±ÄÏÇø\·ïÏè\Ö°ÄÜnpc\Î÷±±ÄÏÇø-·ïÏè¸®-Ç®×¯ÀÏ°å¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Hæ trî T©n Thñ ID: 644 Script: \script\global\namcung\tanthu.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: NhËp CODE ID: 1236 Script: \script\global\dockaka\npcgifcode.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: ÉñÃØÉÌÈËÁøÒÒ ID: 380 Script: \script\global\Â·ÈË_ÉñÃØÉÌÈËÁøÒÒ.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Ìú½³ ID: 198 Script: \script\ÖĞÔ­ÄÏÇø\ÏåÑô\ÏåÑô\npc\ÏåÑô_Ìú½³¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Àñ¹Ù ID: 377 Script: \script\global\Â·ÈË_Àñ¹Ù.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ¤ng Giµ NOEL ID: 644 Script: \script\global\dockaka\ong_gia_noel.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ÄÏ°¶´¬·ò¼× ID: 240 Script: \script\ÖĞÔ­±±Çø\·çÁê¶É\npc\south_boatman1.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Sø gi¶ chuyÓn ph¸i ID: 1877 Script: \script\global\namcung\chuyenphai.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ³µ·ò ID: 237 Script: \script\ÖĞÔ­ÄÏÇø\ÏåÑô\ÏåÑô\npc\ÏåÑô_æäÕ¾³µ·ò¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ´¬·ò ID: 396 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_³¤½­ÂëÍ·´¬·ò¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Hæ trî T©n Thñ ID: 644 Script: \script\global\namcung\tanthu.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ÎâÉñÒ½ ID: 389 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_Ò©µêÀÏ°å¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Áã·· ID: 260 Script: \script\½­ÄÏÇø\ÁÙ°²\ÁÙ°²\npc\Ö°ÄÜ_Ò©··×Ó.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ËÎ¾ü¾üĞè¹Ù ID: 55 Script: \script\global\ÌØÊâÓÃµØ\ËÎ½ğ±¨Ãûµã\npc\song_shop.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 0 Kind: 3"
"Name: Àñ¹Ù ID: 377 Script: \script\global\Â·ÈË_Àñ¹Ù.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ÎâÉñÒ½ ID: 389 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_Ò©µêÀÏ°å¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ÔÓ»õÆÌÀÏ°å ID: 219 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_ÔÓ»õµêÀÏ°å¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ±±°¶´¬·ò±û ID: 240 Script: \script\ÖĞÔ­±±Çø\·çÁê¶É\npc\north_boatman3.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: dua ngua ID: 1877 Script: \script\update_feature\duanguaxephang\npc_quanlyduangua.lua DropFile:  Life: 100 NguHanh: 4 Kind: 3"
"Name: Ng­êi tiÕp dÉn Thiªn Tr× MËt C¶ ID: 312 Script: \script\missions\tianchimijing\floor1\floor1_enternpc.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: di chuyÓn map VIP 2 ID: 309 Script: \script\global\dockaka\mapvip2.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: Thî rÌn ID: 197 Script: \script\missions\tianchimijing\floor2\tiejiang.lua DropFile:  Life: 100 NguHanh: 2 Kind: 3"
"Name: Thî rÌn ID: 197 Script: \script\missions\tianchimijing\floor2\tiejiang.lua DropFile:  Life: 100 NguHanh: 2 Kind: 3"
"Name: ThÇn bİ  thiÕt t­îng ID: 387 Script: \script\½­ÄÏÇø\ÁÙ°²\ÁÙ°²\npc\Ö°ÄÜ_ÉñÃØÌú½³.lua DropFile:  Life: 100 NguHanh: 2 Kind: 3"
"Name: Àñ¹Ù ID: 377 Script: \script\global\Â·ÈË_Àñ¹Ù.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: c·i l·o hoµn ®ång ID: 81 Script: \script\global\dockaka\cailaohoandong.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 2 Kind: 3"
